version: "3.4"

services:
  caddy:
    image: caddy:2.6.4-alpine
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      EMAIL: ${EMAIL:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp
  prod:
    build:
      context: .